version: 2

workflows:
  version: 2
  master:
    jobs:
      - build_develop:
          context: develop
          filters:
            branches:
              only:
                - develop
      - build:
          context: production
          filters:
            branches:
              only:
                - production
      - check_develop:
          context: develop
          requires:
            - build_develop
          filters:
            branches:
              only:
                - develop
      - check:
          context: production
          requires:
            - build
          filters:
            branches:
              only:
                - production
      - image_develop:
          context: develop
          requires:
            - check_develop
          filters:
            branches:
              only:
                - develop
      - image_production:
          context: production
          requires:
            - check
          filters:
            branches:
              only:
                - production
      - deploy_to_develop:
          context: develop
          requires:
            - image_develop
          filters:
            branches:
              only:
                - develop
      - deploy_to_production:
          context: production
          requires:
            - image_production
          filters:
            branches:
              only:
                - production

jobs:
  build:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build project
          command: yarn build
      - persist_to_workspace:
          root: /root/project
          paths:
            - node_modules

  build_develop:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build project
          command: yarn build:development
      - persist_to_workspace:
          root: /root/project
          paths:
            - node_modules

  check:
    docker:
      - image: node:16
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Check project
          command: yarn ci

  check_develop:
    docker:
      - image: node:16
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Check project
          command: yarn ci

  image_develop:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u ${REGISTRY_LOGIN} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
      - run:
          name: Build docker image
          command: docker build -t envoys-frontend . --build-arg environment=beta
      - run:
          name: CHeck pipeline var
          command: |
            echo "Build number: << pipeline.number >>"
      - run:
          name: Publish docker image
          command: |
            echo "Build number: << pipeline.number >>"
            docker tag envoys-frontend "registry.beta.envoys.vision/envoys-frontend:develop-<< pipeline.number >>"
            docker push "registry.beta.envoys.vision/envoys-frontend:develop-<< pipeline.number >>"

  image_production:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u ${REGISTRY_LOGIN} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
      - run:
          name: Build docker image
          command: docker build -t envoys-frontend .
      - run:
          name: Publish docker image
          command: |
            echo "Build number: << pipeline.number >>"
            docker tag envoys-frontend "registry.app.envoys.vision/envoys-frontend:production-<< pipeline.number >>"
            docker push "registry.app.envoys.vision/envoys-frontend:production-<< pipeline.number >>"

  deploy_to_develop:
    docker:
      - image: bash:5-alpine3.15
    steps:
      - checkout
      - run:
          name: Install cURL
          command: apk add curl
      - run:
          name: Run deploy
          command: |
            echo "Deploy number: << pipeline.number >>"
            ./.circleci/deploy.sh "${STACK_FRONTEND}" "<< pipeline.number >>"

  deploy_to_production:
    docker:
      - image: bash:5-alpine3.15
    steps:
      - checkout
      - run:
          name: Install cURL
          command: apk add curl
      - run:
          name: Run deploy
          command: |
            echo "Deploy number: << pipeline.number >>"
            ./.circleci/deploy.sh "${STACK_FRONTEND}" "<< pipeline.number >>"
