version: "3.8"

services:

  app:
    image: registry.beta.envoys.vision/envoys-frontend:develop-${VERSION}
    restart: always
    environment:
      PORT: 3000
    expose:
      - "3000"
    networks:
      - envoys-docker_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`beta.envoys.vision`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"

networks:
  envoys-docker_default:
    external: true
